server:
  port: 9090

spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
#      url contenedor docker:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
#    evitar problemas de resolucion de nombres (para docker en este caso)
    prefer-ip-address: true