spring:
  application:
    name: chatService
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:                          
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: 9100

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
