spring:
  application:
    name: Usuarios

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  file:
    name: logs/usuario.log
server:
  port: 9090