#file: noinspection SpringBootApplicationYaml
spring:
  application:
    name: Orion
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orion_db}
    username: ${SPRING_DATASOURCE_USERNAME:orion}
    password: ${SPRING_DATASOURCE_PASSWORD:orion}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  security:
    user:
      name: akomi
      password: akomi
server:
  port: 8000

