spring:
  application:
    name: Orion
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    datasource:
      url: ${SPRING_DATASOURCE_URL}:jdbc:postgresql://db:5432/${POSTGRES_DB}
      username: ${POSTGRES_USER}:root
      password: ${POSTGRES_PASSWORD}:root