server:
  port: 9092

spring:
  application:
    name: Grupos_service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:

    path: /v3/api-docs