server:
  port: 8000

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true

          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**, /api/test/**
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    prefer-ip-address: true


jwt:
  secret: ${JWT_SECRET}