spring:
  application:
    name: Posteos
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/feed_db?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  file:
    name: logs/Posts.log



jwt:
  secret: ${JWT_SECRET}
  expiration_time: ${JWT_EXPIRATION_TIME}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

server:
  port: 9091
